on: [push, pull_request]
name: Test
jobs:
  test:
    strategy:
      matrix:
        go-version: [1.18.x]
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go-version }}
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Test
      run: go test ./...
    - name: Run GoReleaser
      uses: goreleaser/goreleaser-action@v2
      with:
        # either 'goreleaser' (default) or 'goreleaser-pro'
        distribution: goreleaser
        version: latest
        args: build --rm-dist --snapshot
    - name: Copy files (Ubuntu)
      if: matrix.os == 'ubuntu-latest'
      run: |
        cp dist/stashcp_linux_amd64_v1/stashcp ./
        cp dist/stash_plugin_linux_amd64_v1/stash_plugin ./
    - name: Run Integration Tests
      if: matrix.os == 'ubuntu-latest'
      run: ./tests/citests.sh
